sudo: false
dist: trusty
language: node_js
node_js: 'lts/*'

# greenkeeper support
before_install:
  # package-lock.json was introduced in npm@5
  - npm install -g npm@5 # skip this if you are using node 9
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run cover -- --verbose
after_script: greenkeeper-lockfile-upload

after_success:
  - nyc report --reporter=text-lcov | coveralls

cache:
  directories:
    - node_modules
